// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyfjrigtmryjwwizggyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5ZmpyaWd0bXJ5and3aXpnZ3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTgwODMsImV4cCI6MjA1ODU5NDA4M30.30yUfxLdHDbguJqX8AtTarU3EyxzZdpdET8KGzfGoUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);